package DCSRApp;


/**
* DCSRApp/arrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Modules.idl
* Sunday, November 4, 2018 at 9:57:55 PM Eastern Standard Time
*/

public final class arrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public arrayHolder ()
  {
  }

  public arrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DCSRApp.arrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DCSRApp.arrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DCSRApp.arrayHelper.type ();
  }

}
