package DCSRApp;


import java.io.IOException;

/**
* DCSRApp/DCSRInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Modules.idl
* Sunday, November 4, 2018 at 9:57:55 PM Eastern Standard Time
*/

public abstract class DCSRInterfacePOA extends org.omg.PortableServer.Servant
 implements DCSRApp.DCSRInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addCourse", new java.lang.Integer (0));
    _methods.put ("removeCourse", new java.lang.Integer (1));
    _methods.put ("CourseAvailability", new java.lang.Integer (2));
    _methods.put ("enrolCourse", new java.lang.Integer (3));
    _methods.put ("getClassSchedule", new java.lang.Integer (4));
    _methods.put ("dropCourse", new java.lang.Integer (5));
    _methods.put ("addUserToEnrolledUser", new java.lang.Integer (6));
    _methods.put ("hasCapacity", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DCSRApp/DCSRInterface/addCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         int capacity = in.read_long ();
         String desc = in.read_string ();
         String $result = null;
         $result = this.addCourse (courseID, semester, capacity, desc);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DCSRApp/DCSRInterface/removeCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.removeCourse (courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DCSRApp/DCSRInterface/CourseAvailability
       {
         String semester = in.read_string ();
         String $result[] = null;
         $result = this.CourseAvailability (semester);
         out = $rh.createReply();
         DCSRApp.arrayHelper.write (out, $result);
         break;
       }

       case 3:  // DCSRApp/DCSRInterface/enrolCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.enrolCourse (studentID, courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DCSRApp/DCSRInterface/getClassSchedule
       {
         String studentID = in.read_string ();
         String $result[] = null;
         $result = this.getClassSchedule (studentID);
         out = $rh.createReply();
         DCSRApp.arrayHelper.write (out, $result);
         break;
       }

       case 5:  // DCSRApp/DCSRInterface/dropCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String $result = null;
         $result = this.dropCourse (studentID, courseID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DCSRApp/DCSRInterface/addUserToEnrolledUser
       {
         String name = in.read_string ();
         String id = in.read_string ();
         String $result = null;
           try {
               $result = this.addUserToEnrolledUser (name, id);
           } catch (IOException e) {
               e.printStackTrace();
           }
           out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DCSRApp/DCSRInterface/hasCapacity
       {
         String courseID = in.read_string ();
         boolean $result = false;
         $result = this.hasCapacity (courseID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // DCSRApp/DCSRInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DCSRApp/DCSRInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DCSRInterface _this() 
  {
    return DCSRInterfaceHelper.narrow(
    super._this_object());
  }

  public DCSRInterface _this(org.omg.CORBA.ORB orb) 
  {
    return DCSRInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class DCSRInterfacePOA
