/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ADivideMultExpr extends PMultExpr
{
    private PMultExpr _multExpr_;
    private TDiv _div_;
    private PUnaryExpr _unaryExpr_;

    public ADivideMultExpr()
    {
    }

    public ADivideMultExpr(
        PMultExpr _multExpr_,
        TDiv _div_,
        PUnaryExpr _unaryExpr_)
    {
        setMultExpr(_multExpr_);

        setDiv(_div_);

        setUnaryExpr(_unaryExpr_);

    }
    public Object clone()
    {
        return new ADivideMultExpr(
            (PMultExpr) cloneNode(_multExpr_),
            (TDiv) cloneNode(_div_),
            (PUnaryExpr) cloneNode(_unaryExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivideMultExpr(this);
    }

    public PMultExpr getMultExpr()
    {
        return _multExpr_;
    }

    public void setMultExpr(PMultExpr node)
    {
        if(_multExpr_ != null)
        {
            _multExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multExpr_ = node;
    }

    public TDiv getDiv()
    {
        return _div_;
    }

    public void setDiv(TDiv node)
    {
        if(_div_ != null)
        {
            _div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _div_ = node;
    }

    public PUnaryExpr getUnaryExpr()
    {
        return _unaryExpr_;
    }

    public void setUnaryExpr(PUnaryExpr node)
    {
        if(_unaryExpr_ != null)
        {
            _unaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_multExpr_)
            + toString(_div_)
            + toString(_unaryExpr_);
    }

    void removeChild(Node child)
    {
        if(_multExpr_ == child)
        {
            _multExpr_ = null;
            return;
        }

        if(_div_ == child)
        {
            _div_ = null;
            return;
        }

        if(_unaryExpr_ == child)
        {
            _unaryExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_multExpr_ == oldChild)
        {
            setMultExpr((PMultExpr) newChild);
            return;
        }

        if(_div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(_unaryExpr_ == oldChild)
        {
            setUnaryExpr((PUnaryExpr) newChild);
            return;
        }

    }
}
