/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AExceptDclDefinition extends PDefinition
{
    private PExceptDcl _exceptDcl_;
    private TSemicolon _semicolon_;

    public AExceptDclDefinition()
    {
    }

    public AExceptDclDefinition(
        PExceptDcl _exceptDcl_,
        TSemicolon _semicolon_)
    {
        setExceptDcl(_exceptDcl_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AExceptDclDefinition(
            (PExceptDcl) cloneNode(_exceptDcl_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExceptDclDefinition(this);
    }

    public PExceptDcl getExceptDcl()
    {
        return _exceptDcl_;
    }

    public void setExceptDcl(PExceptDcl node)
    {
        if(_exceptDcl_ != null)
        {
            _exceptDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exceptDcl_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exceptDcl_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_exceptDcl_ == child)
        {
            _exceptDcl_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exceptDcl_ == oldChild)
        {
            setExceptDcl((PExceptDcl) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
