/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AFixedLiteral extends PLiteral
{
    private TFixedPtLiteral _fixedPtLiteral_;

    public AFixedLiteral()
    {
    }

    public AFixedLiteral(
        TFixedPtLiteral _fixedPtLiteral_)
    {
        setFixedPtLiteral(_fixedPtLiteral_);

    }
    public Object clone()
    {
        return new AFixedLiteral(
            (TFixedPtLiteral) cloneNode(_fixedPtLiteral_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFixedLiteral(this);
    }

    public TFixedPtLiteral getFixedPtLiteral()
    {
        return _fixedPtLiteral_;
    }

    public void setFixedPtLiteral(TFixedPtLiteral node)
    {
        if(_fixedPtLiteral_ != null)
        {
            _fixedPtLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _fixedPtLiteral_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_fixedPtLiteral_);
    }

    void removeChild(Node child)
    {
        if(_fixedPtLiteral_ == child)
        {
            _fixedPtLiteral_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_fixedPtLiteral_ == oldChild)
        {
            setFixedPtLiteral((TFixedPtLiteral) newChild);
            return;
        }

    }
}
