/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AFixedConstType extends PConstType
{
    private TFixed _fixed_;

    public AFixedConstType()
    {
    }

    public AFixedConstType(
        TFixed _fixed_)
    {
        setFixed(_fixed_);

    }
    public Object clone()
    {
        return new AFixedConstType(
            (TFixed) cloneNode(_fixed_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFixedConstType(this);
    }

    public TFixed getFixed()
    {
        return _fixed_;
    }

    public void setFixed(TFixed node)
    {
        if(_fixed_ != null)
        {
            _fixed_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _fixed_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_fixed_);
    }

    void removeChild(Node child)
    {
        if(_fixed_ == child)
        {
            _fixed_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_fixed_ == oldChild)
        {
            setFixed((TFixed) newChild);
            return;
        }

    }
}
