/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AFloatFloatingPtType extends PFloatingPtType
{
    private TFloat _float_;

    public AFloatFloatingPtType()
    {
    }

    public AFloatFloatingPtType(
        TFloat _float_)
    {
        setFloat(_float_);

    }
    public Object clone()
    {
        return new AFloatFloatingPtType(
            (TFloat) cloneNode(_float_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatFloatingPtType(this);
    }

    public TFloat getFloat()
    {
        return _float_;
    }

    public void setFloat(TFloat node)
    {
        if(_float_ != null)
        {
            _float_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _float_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_float_);
    }

    void removeChild(Node child)
    {
        if(_float_ == child)
        {
            _float_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_float_ == oldChild)
        {
            setFloat((TFloat) newChild);
            return;
        }

    }
}
