/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AForwardDclStructType extends PStructType
{
    private PStructForwardDcl _structForwardDcl_;

    public AForwardDclStructType()
    {
    }

    public AForwardDclStructType(
        PStructForwardDcl _structForwardDcl_)
    {
        setStructForwardDcl(_structForwardDcl_);

    }
    public Object clone()
    {
        return new AForwardDclStructType(
            (PStructForwardDcl) cloneNode(_structForwardDcl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForwardDclStructType(this);
    }

    public PStructForwardDcl getStructForwardDcl()
    {
        return _structForwardDcl_;
    }

    public void setStructForwardDcl(PStructForwardDcl node)
    {
        if(_structForwardDcl_ != null)
        {
            _structForwardDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _structForwardDcl_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_structForwardDcl_);
    }

    void removeChild(Node child)
    {
        if(_structForwardDcl_ == child)
        {
            _structForwardDcl_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_structForwardDcl_ == oldChild)
        {
            setStructForwardDcl((PStructForwardDcl) newChild);
            return;
        }

    }
}
