/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AIdlInterfaceDefinition extends PDefinition
{
    private PIdlInterface _idlInterface_;
    private TSemicolon _semicolon_;

    public AIdlInterfaceDefinition()
    {
    }

    public AIdlInterfaceDefinition(
        PIdlInterface _idlInterface_,
        TSemicolon _semicolon_)
    {
        setIdlInterface(_idlInterface_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AIdlInterfaceDefinition(
            (PIdlInterface) cloneNode(_idlInterface_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdlInterfaceDefinition(this);
    }

    public PIdlInterface getIdlInterface()
    {
        return _idlInterface_;
    }

    public void setIdlInterface(PIdlInterface node)
    {
        if(_idlInterface_ != null)
        {
            _idlInterface_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _idlInterface_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_idlInterface_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_idlInterface_ == child)
        {
            _idlInterface_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_idlInterface_ == oldChild)
        {
            setIdlInterface((PIdlInterface) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
