/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AIdlModule extends PIdlModule
{
    private TModule _module_;
    private TIdentifier _identifier_;
    private TLBrace _lBrace_;
    private final LinkedList _definition_ = new TypedLinkedList(new Definition_Cast());
    private TRBrace _rBrace_;

    public AIdlModule()
    {
    }

    public AIdlModule(
        TModule _module_,
        TIdentifier _identifier_,
        TLBrace _lBrace_,
        List _definition_,
        TRBrace _rBrace_)
    {
        setModule(_module_);

        setIdentifier(_identifier_);

        setLBrace(_lBrace_);

        {
            this._definition_.clear();
            this._definition_.addAll(_definition_);
        }

        setRBrace(_rBrace_);

    }

    public AIdlModule(
        TModule _module_,
        TIdentifier _identifier_,
        TLBrace _lBrace_,
        XPDefinition _definition_,
        TRBrace _rBrace_)
    {
        setModule(_module_);

        setIdentifier(_identifier_);

        setLBrace(_lBrace_);

        if(_definition_ != null)
        {
            while(_definition_ instanceof X1PDefinition)
            {
                this._definition_.addFirst(((X1PDefinition) _definition_).getPDefinition());
                _definition_ = ((X1PDefinition) _definition_).getXPDefinition();
            }
            this._definition_.addFirst(((X2PDefinition) _definition_).getPDefinition());
        }

        setRBrace(_rBrace_);

    }
    public Object clone()
    {
        return new AIdlModule(
            (TModule) cloneNode(_module_),
            (TIdentifier) cloneNode(_identifier_),
            (TLBrace) cloneNode(_lBrace_),
            cloneList(_definition_),
            (TRBrace) cloneNode(_rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdlModule(this);
    }

    public TModule getModule()
    {
        return _module_;
    }

    public void setModule(TModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TLBrace getLBrace()
    {
        return _lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(_lBrace_ != null)
        {
            _lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBrace_ = node;
    }

    public LinkedList getDefinition()
    {
        return _definition_;
    }

    public void setDefinition(List list)
    {
        _definition_.clear();
        _definition_.addAll(list);
    }

    public TRBrace getRBrace()
    {
        return _rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(_rBrace_ != null)
        {
            _rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBrace_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_module_)
            + toString(_identifier_)
            + toString(_lBrace_)
            + toString(_definition_)
            + toString(_rBrace_);
    }

    void removeChild(Node child)
    {
        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_lBrace_ == child)
        {
            _lBrace_ = null;
            return;
        }

        if(_definition_.remove(child))
        {
            return;
        }

        if(_rBrace_ == child)
        {
            _rBrace_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_module_ == oldChild)
        {
            setModule((TModule) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        for(ListIterator i = _definition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

    }

    private class Definition_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PDefinition node = (PDefinition) o;

            if((node.parent() != null) &&
                (node.parent() != AIdlModule.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AIdlModule.this))
            {
                node.parent(AIdlModule.this);
            }

            return node;
        }
    }
}
