/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AIdlModuleDefinition extends PDefinition
{
    private PIdlModule _idlModule_;
    private TSemicolon _semicolon_;

    public AIdlModuleDefinition()
    {
    }

    public AIdlModuleDefinition(
        PIdlModule _idlModule_,
        TSemicolon _semicolon_)
    {
        setIdlModule(_idlModule_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AIdlModuleDefinition(
            (PIdlModule) cloneNode(_idlModule_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdlModuleDefinition(this);
    }

    public PIdlModule getIdlModule()
    {
        return _idlModule_;
    }

    public void setIdlModule(PIdlModule node)
    {
        if(_idlModule_ != null)
        {
            _idlModule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _idlModule_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_idlModule_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_idlModule_ == child)
        {
            _idlModule_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_idlModule_ == oldChild)
        {
            setIdlModule((PIdlModule) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
