/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AInitDclValueElement extends PValueElement
{
    private PInitDcl _initDcl_;

    public AInitDclValueElement()
    {
    }

    public AInitDclValueElement(
        PInitDcl _initDcl_)
    {
        setInitDcl(_initDcl_);

    }
    public Object clone()
    {
        return new AInitDclValueElement(
            (PInitDcl) cloneNode(_initDcl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitDclValueElement(this);
    }

    public PInitDcl getInitDcl()
    {
        return _initDcl_;
    }

    public void setInitDcl(PInitDcl node)
    {
        if(_initDcl_ != null)
        {
            _initDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _initDcl_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_initDcl_);
    }

    void removeChild(Node child)
    {
        if(_initDcl_ == child)
        {
            _initDcl_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_initDcl_ == oldChild)
        {
            setInitDcl((PInitDcl) newChild);
            return;
        }

    }
}
