/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AInoutParamAttribute extends PParamAttribute
{
    private TInout _inout_;

    public AInoutParamAttribute()
    {
    }

    public AInoutParamAttribute(
        TInout _inout_)
    {
        setInout(_inout_);

    }
    public Object clone()
    {
        return new AInoutParamAttribute(
            (TInout) cloneNode(_inout_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInoutParamAttribute(this);
    }

    public TInout getInout()
    {
        return _inout_;
    }

    public void setInout(TInout node)
    {
        if(_inout_ != null)
        {
            _inout_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inout_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_inout_);
    }

    void removeChild(Node child)
    {
        if(_inout_ == child)
        {
            _inout_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_inout_ == oldChild)
        {
            setInout((TInout) newChild);
            return;
        }

    }
}
