/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AInterfaceInheritanceSpec extends PInterfaceInheritanceSpec
{
    private TColon _colon_;
    private PScopedName _scopedName_;
    private final LinkedList _commaScopedName_ = new TypedLinkedList(new CommaScopedName_Cast());

    public AInterfaceInheritanceSpec()
    {
    }

    public AInterfaceInheritanceSpec(
        TColon _colon_,
        PScopedName _scopedName_,
        List _commaScopedName_)
    {
        setColon(_colon_);

        setScopedName(_scopedName_);

        {
            this._commaScopedName_.clear();
            this._commaScopedName_.addAll(_commaScopedName_);
        }

    }

    public AInterfaceInheritanceSpec(
        TColon _colon_,
        PScopedName _scopedName_,
        XPCommaScopedName _commaScopedName_)
    {
        setColon(_colon_);

        setScopedName(_scopedName_);

        if(_commaScopedName_ != null)
        {
            while(_commaScopedName_ instanceof X1PCommaScopedName)
            {
                this._commaScopedName_.addFirst(((X1PCommaScopedName) _commaScopedName_).getPCommaScopedName());
                _commaScopedName_ = ((X1PCommaScopedName) _commaScopedName_).getXPCommaScopedName();
            }
            this._commaScopedName_.addFirst(((X2PCommaScopedName) _commaScopedName_).getPCommaScopedName());
        }

    }
    public Object clone()
    {
        return new AInterfaceInheritanceSpec(
            (TColon) cloneNode(_colon_),
            (PScopedName) cloneNode(_scopedName_),
            cloneList(_commaScopedName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInterfaceInheritanceSpec(this);
    }

    public TColon getColon()
    {
        return _colon_;
    }

    public void setColon(TColon node)
    {
        if(_colon_ != null)
        {
            _colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _colon_ = node;
    }

    public PScopedName getScopedName()
    {
        return _scopedName_;
    }

    public void setScopedName(PScopedName node)
    {
        if(_scopedName_ != null)
        {
            _scopedName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _scopedName_ = node;
    }

    public LinkedList getCommaScopedName()
    {
        return _commaScopedName_;
    }

    public void setCommaScopedName(List list)
    {
        _commaScopedName_.clear();
        _commaScopedName_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_colon_)
            + toString(_scopedName_)
            + toString(_commaScopedName_);
    }

    void removeChild(Node child)
    {
        if(_colon_ == child)
        {
            _colon_ = null;
            return;
        }

        if(_scopedName_ == child)
        {
            _scopedName_ = null;
            return;
        }

        if(_commaScopedName_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(_scopedName_ == oldChild)
        {
            setScopedName((PScopedName) newChild);
            return;
        }

        for(ListIterator i = _commaScopedName_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class CommaScopedName_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaScopedName node = (PCommaScopedName) o;

            if((node.parent() != null) &&
                (node.parent() != AInterfaceInheritanceSpec.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AInterfaceInheritanceSpec.this))
            {
                node.parent(AInterfaceInheritanceSpec.this);
            }

            return node;
        }
    }
}
