/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AInterfaceDcl extends PInterfaceDcl
{
    private PInterfaceHeader _interfaceHeader_;
    private TLBrace _lBrace_;
    private final LinkedList _export_ = new TypedLinkedList(new Export_Cast());
    private TRBrace _rBrace_;

    public AInterfaceDcl()
    {
    }

    public AInterfaceDcl(
        PInterfaceHeader _interfaceHeader_,
        TLBrace _lBrace_,
        List _export_,
        TRBrace _rBrace_)
    {
        setInterfaceHeader(_interfaceHeader_);

        setLBrace(_lBrace_);

        {
            this._export_.clear();
            this._export_.addAll(_export_);
        }

        setRBrace(_rBrace_);

    }

    public AInterfaceDcl(
        PInterfaceHeader _interfaceHeader_,
        TLBrace _lBrace_,
        XPExport _export_,
        TRBrace _rBrace_)
    {
        setInterfaceHeader(_interfaceHeader_);

        setLBrace(_lBrace_);

        if(_export_ != null)
        {
            while(_export_ instanceof X1PExport)
            {
                this._export_.addFirst(((X1PExport) _export_).getPExport());
                _export_ = ((X1PExport) _export_).getXPExport();
            }
            this._export_.addFirst(((X2PExport) _export_).getPExport());
        }

        setRBrace(_rBrace_);

    }
    public Object clone()
    {
        return new AInterfaceDcl(
            (PInterfaceHeader) cloneNode(_interfaceHeader_),
            (TLBrace) cloneNode(_lBrace_),
            cloneList(_export_),
            (TRBrace) cloneNode(_rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInterfaceDcl(this);
    }

    public PInterfaceHeader getInterfaceHeader()
    {
        return _interfaceHeader_;
    }

    public void setInterfaceHeader(PInterfaceHeader node)
    {
        if(_interfaceHeader_ != null)
        {
            _interfaceHeader_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _interfaceHeader_ = node;
    }

    public TLBrace getLBrace()
    {
        return _lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(_lBrace_ != null)
        {
            _lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBrace_ = node;
    }

    public LinkedList getExport()
    {
        return _export_;
    }

    public void setExport(List list)
    {
        _export_.clear();
        _export_.addAll(list);
    }

    public TRBrace getRBrace()
    {
        return _rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(_rBrace_ != null)
        {
            _rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBrace_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_interfaceHeader_)
            + toString(_lBrace_)
            + toString(_export_)
            + toString(_rBrace_);
    }

    void removeChild(Node child)
    {
        if(_interfaceHeader_ == child)
        {
            _interfaceHeader_ = null;
            return;
        }

        if(_lBrace_ == child)
        {
            _lBrace_ = null;
            return;
        }

        if(_export_.remove(child))
        {
            return;
        }

        if(_rBrace_ == child)
        {
            _rBrace_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_interfaceHeader_ == oldChild)
        {
            setInterfaceHeader((PInterfaceHeader) newChild);
            return;
        }

        if(_lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        for(ListIterator i = _export_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

    }

    private class Export_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExport node = (PExport) o;

            if((node.parent() != null) &&
                (node.parent() != AInterfaceDcl.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AInterfaceDcl.this))
            {
                node.parent(AInterfaceDcl.this);
            }

            return node;
        }
    }
}
