/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AInterfaceHeader extends PInterfaceHeader
{
    private PForwardDcl _forwardDcl_;
    private PInterfaceInheritanceSpec _interfaceInheritanceSpec_;

    public AInterfaceHeader()
    {
    }

    public AInterfaceHeader(
        PForwardDcl _forwardDcl_,
        PInterfaceInheritanceSpec _interfaceInheritanceSpec_)
    {
        setForwardDcl(_forwardDcl_);

        setInterfaceInheritanceSpec(_interfaceInheritanceSpec_);

    }
    public Object clone()
    {
        return new AInterfaceHeader(
            (PForwardDcl) cloneNode(_forwardDcl_),
            (PInterfaceInheritanceSpec) cloneNode(_interfaceInheritanceSpec_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInterfaceHeader(this);
    }

    public PForwardDcl getForwardDcl()
    {
        return _forwardDcl_;
    }

    public void setForwardDcl(PForwardDcl node)
    {
        if(_forwardDcl_ != null)
        {
            _forwardDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _forwardDcl_ = node;
    }

    public PInterfaceInheritanceSpec getInterfaceInheritanceSpec()
    {
        return _interfaceInheritanceSpec_;
    }

    public void setInterfaceInheritanceSpec(PInterfaceInheritanceSpec node)
    {
        if(_interfaceInheritanceSpec_ != null)
        {
            _interfaceInheritanceSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _interfaceInheritanceSpec_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_forwardDcl_)
            + toString(_interfaceInheritanceSpec_);
    }

    void removeChild(Node child)
    {
        if(_forwardDcl_ == child)
        {
            _forwardDcl_ = null;
            return;
        }

        if(_interfaceInheritanceSpec_ == child)
        {
            _interfaceInheritanceSpec_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_forwardDcl_ == oldChild)
        {
            setForwardDcl((PForwardDcl) newChild);
            return;
        }

        if(_interfaceInheritanceSpec_ == oldChild)
        {
            setInterfaceInheritanceSpec((PInterfaceInheritanceSpec) newChild);
            return;
        }

    }
}
