/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AInterfaceDclIdlInterface extends PIdlInterface
{
    private PInterfaceDcl _interfaceDcl_;

    public AInterfaceDclIdlInterface()
    {
    }

    public AInterfaceDclIdlInterface(
        PInterfaceDcl _interfaceDcl_)
    {
        setInterfaceDcl(_interfaceDcl_);

    }
    public Object clone()
    {
        return new AInterfaceDclIdlInterface(
            (PInterfaceDcl) cloneNode(_interfaceDcl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInterfaceDclIdlInterface(this);
    }

    public PInterfaceDcl getInterfaceDcl()
    {
        return _interfaceDcl_;
    }

    public void setInterfaceDcl(PInterfaceDcl node)
    {
        if(_interfaceDcl_ != null)
        {
            _interfaceDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _interfaceDcl_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_interfaceDcl_);
    }

    void removeChild(Node child)
    {
        if(_interfaceDcl_ == child)
        {
            _interfaceDcl_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_interfaceDcl_ == oldChild)
        {
            setInterfaceDcl((PInterfaceDcl) newChild);
            return;
        }

    }
}
