/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ALocalInterfaceModifier extends PInterfaceModifier
{
    private TLocal _local_;

    public ALocalInterfaceModifier()
    {
    }

    public ALocalInterfaceModifier(
        TLocal _local_)
    {
        setLocal(_local_);

    }
    public Object clone()
    {
        return new ALocalInterfaceModifier(
            (TLocal) cloneNode(_local_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALocalInterfaceModifier(this);
    }

    public TLocal getLocal()
    {
        return _local_;
    }

    public void setLocal(TLocal node)
    {
        if(_local_ != null)
        {
            _local_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _local_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_local_);
    }

    void removeChild(Node child)
    {
        if(_local_ == child)
        {
            _local_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_local_ == oldChild)
        {
            setLocal((TLocal) newChild);
            return;
        }

    }
}
