/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ALondDoubleFloatingPtType extends PFloatingPtType
{
    private TLong _long_;
    private TDouble _double_;

    public ALondDoubleFloatingPtType()
    {
    }

    public ALondDoubleFloatingPtType(
        TLong _long_,
        TDouble _double_)
    {
        setLong(_long_);

        setDouble(_double_);

    }
    public Object clone()
    {
        return new ALondDoubleFloatingPtType(
            (TLong) cloneNode(_long_),
            (TDouble) cloneNode(_double_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALondDoubleFloatingPtType(this);
    }

    public TLong getLong()
    {
        return _long_;
    }

    public void setLong(TLong node)
    {
        if(_long_ != null)
        {
            _long_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _long_ = node;
    }

    public TDouble getDouble()
    {
        return _double_;
    }

    public void setDouble(TDouble node)
    {
        if(_double_ != null)
        {
            _double_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _double_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_long_)
            + toString(_double_);
    }

    void removeChild(Node child)
    {
        if(_long_ == child)
        {
            _long_ = null;
            return;
        }

        if(_double_ == child)
        {
            _double_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_long_ == oldChild)
        {
            setLong((TLong) newChild);
            return;
        }

        if(_double_ == oldChild)
        {
            setDouble((TDouble) newChild);
            return;
        }

    }
}
