/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AMember extends PMember
{
    private PTypeSpec _typeSpec_;
    private PDeclarators _declarators_;
    private TSemicolon _semicolon_;

    public AMember()
    {
    }

    public AMember(
        PTypeSpec _typeSpec_,
        PDeclarators _declarators_,
        TSemicolon _semicolon_)
    {
        setTypeSpec(_typeSpec_);

        setDeclarators(_declarators_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AMember(
            (PTypeSpec) cloneNode(_typeSpec_),
            (PDeclarators) cloneNode(_declarators_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMember(this);
    }

    public PTypeSpec getTypeSpec()
    {
        return _typeSpec_;
    }

    public void setTypeSpec(PTypeSpec node)
    {
        if(_typeSpec_ != null)
        {
            _typeSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _typeSpec_ = node;
    }

    public PDeclarators getDeclarators()
    {
        return _declarators_;
    }

    public void setDeclarators(PDeclarators node)
    {
        if(_declarators_ != null)
        {
            _declarators_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _declarators_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_typeSpec_)
            + toString(_declarators_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_typeSpec_ == child)
        {
            _typeSpec_ = null;
            return;
        }

        if(_declarators_ == child)
        {
            _declarators_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_typeSpec_ == oldChild)
        {
            setTypeSpec((PTypeSpec) newChild);
            return;
        }

        if(_declarators_ == oldChild)
        {
            setDeclarators((PDeclarators) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
