/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AMinusAddExpr extends PAddExpr
{
    private PAddExpr _addExpr_;
    private TMinus _minus_;
    private PMultExpr _multExpr_;

    public AMinusAddExpr()
    {
    }

    public AMinusAddExpr(
        PAddExpr _addExpr_,
        TMinus _minus_,
        PMultExpr _multExpr_)
    {
        setAddExpr(_addExpr_);

        setMinus(_minus_);

        setMultExpr(_multExpr_);

    }
    public Object clone()
    {
        return new AMinusAddExpr(
            (PAddExpr) cloneNode(_addExpr_),
            (TMinus) cloneNode(_minus_),
            (PMultExpr) cloneNode(_multExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusAddExpr(this);
    }

    public PAddExpr getAddExpr()
    {
        return _addExpr_;
    }

    public void setAddExpr(PAddExpr node)
    {
        if(_addExpr_ != null)
        {
            _addExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _addExpr_ = node;
    }

    public TMinus getMinus()
    {
        return _minus_;
    }

    public void setMinus(TMinus node)
    {
        if(_minus_ != null)
        {
            _minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minus_ = node;
    }

    public PMultExpr getMultExpr()
    {
        return _multExpr_;
    }

    public void setMultExpr(PMultExpr node)
    {
        if(_multExpr_ != null)
        {
            _multExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_addExpr_)
            + toString(_minus_)
            + toString(_multExpr_);
    }

    void removeChild(Node child)
    {
        if(_addExpr_ == child)
        {
            _addExpr_ = null;
            return;
        }

        if(_minus_ == child)
        {
            _minus_ = null;
            return;
        }

        if(_multExpr_ == child)
        {
            _multExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_addExpr_ == oldChild)
        {
            setAddExpr((PAddExpr) newChild);
            return;
        }

        if(_minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(_multExpr_ == oldChild)
        {
            setMultExpr((PMultExpr) newChild);
            return;
        }

    }
}
