/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AModMultExpr extends PMultExpr
{
    private PMultExpr _multExpr_;
    private TMod _mod_;
    private PUnaryExpr _unaryExpr_;

    public AModMultExpr()
    {
    }

    public AModMultExpr(
        PMultExpr _multExpr_,
        TMod _mod_,
        PUnaryExpr _unaryExpr_)
    {
        setMultExpr(_multExpr_);

        setMod(_mod_);

        setUnaryExpr(_unaryExpr_);

    }
    public Object clone()
    {
        return new AModMultExpr(
            (PMultExpr) cloneNode(_multExpr_),
            (TMod) cloneNode(_mod_),
            (PUnaryExpr) cloneNode(_unaryExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModMultExpr(this);
    }

    public PMultExpr getMultExpr()
    {
        return _multExpr_;
    }

    public void setMultExpr(PMultExpr node)
    {
        if(_multExpr_ != null)
        {
            _multExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multExpr_ = node;
    }

    public TMod getMod()
    {
        return _mod_;
    }

    public void setMod(TMod node)
    {
        if(_mod_ != null)
        {
            _mod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mod_ = node;
    }

    public PUnaryExpr getUnaryExpr()
    {
        return _unaryExpr_;
    }

    public void setUnaryExpr(PUnaryExpr node)
    {
        if(_unaryExpr_ != null)
        {
            _unaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_multExpr_)
            + toString(_mod_)
            + toString(_unaryExpr_);
    }

    void removeChild(Node child)
    {
        if(_multExpr_ == child)
        {
            _multExpr_ = null;
            return;
        }

        if(_mod_ == child)
        {
            _mod_ = null;
            return;
        }

        if(_unaryExpr_ == child)
        {
            _unaryExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_multExpr_ == oldChild)
        {
            setMultExpr((PMultExpr) newChild);
            return;
        }

        if(_mod_ == oldChild)
        {
            setMod((TMod) newChild);
            return;
        }

        if(_unaryExpr_ == oldChild)
        {
            setUnaryExpr((PUnaryExpr) newChild);
            return;
        }

    }
}
