/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AMsupportValueInheritanceSpec extends PValueInheritanceSpec
{
    private TColon _colon_;
    private TTruncatable _truncatable_;
    private PScopedName _scopedName_;
    private final LinkedList _commaScopedName_ = new TypedLinkedList(new CommaScopedName_Cast());
    private TSupports _supports_;
    private PScopedName _supportScoped_;
    private final LinkedList _supportCommaSupport_ = new TypedLinkedList(new SupportCommaSupport_Cast());

    public AMsupportValueInheritanceSpec()
    {
    }

    public AMsupportValueInheritanceSpec(
        TColon _colon_,
        TTruncatable _truncatable_,
        PScopedName _scopedName_,
        List _commaScopedName_,
        TSupports _supports_,
        PScopedName _supportScoped_,
        List _supportCommaSupport_)
    {
        setColon(_colon_);

        setTruncatable(_truncatable_);

        setScopedName(_scopedName_);

        {
            this._commaScopedName_.clear();
            this._commaScopedName_.addAll(_commaScopedName_);
        }

        setSupports(_supports_);

        setSupportScoped(_supportScoped_);

        {
            this._supportCommaSupport_.clear();
            this._supportCommaSupport_.addAll(_supportCommaSupport_);
        }

    }

    public AMsupportValueInheritanceSpec(
        TColon _colon_,
        TTruncatable _truncatable_,
        PScopedName _scopedName_,
        XPCommaScopedName _commaScopedName_,
        TSupports _supports_,
        PScopedName _supportScoped_,
        XPCommaScopedName _supportCommaSupport_)
    {
        setColon(_colon_);

        setTruncatable(_truncatable_);

        setScopedName(_scopedName_);

        if(_commaScopedName_ != null)
        {
            while(_commaScopedName_ instanceof X1PCommaScopedName)
            {
                this._commaScopedName_.addFirst(((X1PCommaScopedName) _commaScopedName_).getPCommaScopedName());
                _commaScopedName_ = ((X1PCommaScopedName) _commaScopedName_).getXPCommaScopedName();
            }
            this._commaScopedName_.addFirst(((X2PCommaScopedName) _commaScopedName_).getPCommaScopedName());
        }

        setSupports(_supports_);

        setSupportScoped(_supportScoped_);

        if(_supportCommaSupport_ != null)
        {
            while(_supportCommaSupport_ instanceof X1PCommaScopedName)
            {
                this._supportCommaSupport_.addFirst(((X1PCommaScopedName) _supportCommaSupport_).getPCommaScopedName());
                _supportCommaSupport_ = ((X1PCommaScopedName) _supportCommaSupport_).getXPCommaScopedName();
            }
            this._supportCommaSupport_.addFirst(((X2PCommaScopedName) _supportCommaSupport_).getPCommaScopedName());
        }

    }
    public Object clone()
    {
        return new AMsupportValueInheritanceSpec(
            (TColon) cloneNode(_colon_),
            (TTruncatable) cloneNode(_truncatable_),
            (PScopedName) cloneNode(_scopedName_),
            cloneList(_commaScopedName_),
            (TSupports) cloneNode(_supports_),
            (PScopedName) cloneNode(_supportScoped_),
            cloneList(_supportCommaSupport_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMsupportValueInheritanceSpec(this);
    }

    public TColon getColon()
    {
        return _colon_;
    }

    public void setColon(TColon node)
    {
        if(_colon_ != null)
        {
            _colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _colon_ = node;
    }

    public TTruncatable getTruncatable()
    {
        return _truncatable_;
    }

    public void setTruncatable(TTruncatable node)
    {
        if(_truncatable_ != null)
        {
            _truncatable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _truncatable_ = node;
    }

    public PScopedName getScopedName()
    {
        return _scopedName_;
    }

    public void setScopedName(PScopedName node)
    {
        if(_scopedName_ != null)
        {
            _scopedName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _scopedName_ = node;
    }

    public LinkedList getCommaScopedName()
    {
        return _commaScopedName_;
    }

    public void setCommaScopedName(List list)
    {
        _commaScopedName_.clear();
        _commaScopedName_.addAll(list);
    }

    public TSupports getSupports()
    {
        return _supports_;
    }

    public void setSupports(TSupports node)
    {
        if(_supports_ != null)
        {
            _supports_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _supports_ = node;
    }

    public PScopedName getSupportScoped()
    {
        return _supportScoped_;
    }

    public void setSupportScoped(PScopedName node)
    {
        if(_supportScoped_ != null)
        {
            _supportScoped_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _supportScoped_ = node;
    }

    public LinkedList getSupportCommaSupport()
    {
        return _supportCommaSupport_;
    }

    public void setSupportCommaSupport(List list)
    {
        _supportCommaSupport_.clear();
        _supportCommaSupport_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_colon_)
            + toString(_truncatable_)
            + toString(_scopedName_)
            + toString(_commaScopedName_)
            + toString(_supports_)
            + toString(_supportScoped_)
            + toString(_supportCommaSupport_);
    }

    void removeChild(Node child)
    {
        if(_colon_ == child)
        {
            _colon_ = null;
            return;
        }

        if(_truncatable_ == child)
        {
            _truncatable_ = null;
            return;
        }

        if(_scopedName_ == child)
        {
            _scopedName_ = null;
            return;
        }

        if(_commaScopedName_.remove(child))
        {
            return;
        }

        if(_supports_ == child)
        {
            _supports_ = null;
            return;
        }

        if(_supportScoped_ == child)
        {
            _supportScoped_ = null;
            return;
        }

        if(_supportCommaSupport_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(_truncatable_ == oldChild)
        {
            setTruncatable((TTruncatable) newChild);
            return;
        }

        if(_scopedName_ == oldChild)
        {
            setScopedName((PScopedName) newChild);
            return;
        }

        for(ListIterator i = _commaScopedName_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_supports_ == oldChild)
        {
            setSupports((TSupports) newChild);
            return;
        }

        if(_supportScoped_ == oldChild)
        {
            setSupportScoped((PScopedName) newChild);
            return;
        }

        for(ListIterator i = _supportCommaSupport_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class CommaScopedName_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaScopedName node = (PCommaScopedName) o;

            if((node.parent() != null) &&
                (node.parent() != AMsupportValueInheritanceSpec.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AMsupportValueInheritanceSpec.this))
            {
                node.parent(AMsupportValueInheritanceSpec.this);
            }

            return node;
        }
    }

    private class SupportCommaSupport_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaScopedName node = (PCommaScopedName) o;

            if((node.parent() != null) &&
                (node.parent() != AMsupportValueInheritanceSpec.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AMsupportValueInheritanceSpec.this))
            {
                node.parent(AMsupportValueInheritanceSpec.this);
            }

            return node;
        }
    }
}
