/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AOctetConstType extends PConstType
{
    private TOctet _octet_;

    public AOctetConstType()
    {
    }

    public AOctetConstType(
        TOctet _octet_)
    {
        setOctet(_octet_);

    }
    public Object clone()
    {
        return new AOctetConstType(
            (TOctet) cloneNode(_octet_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOctetConstType(this);
    }

    public TOctet getOctet()
    {
        return _octet_;
    }

    public void setOctet(TOctet node)
    {
        if(_octet_ != null)
        {
            _octet_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _octet_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_octet_);
    }

    void removeChild(Node child)
    {
        if(_octet_ == child)
        {
            _octet_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_octet_ == oldChild)
        {
            setOctet((TOctet) newChild);
            return;
        }

    }
}
