/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AOrExprCaseLabel extends PCaseLabel
{
    private TCase _case_;
    private POrExpr _orExpr_;
    private TColon _colon_;

    public AOrExprCaseLabel()
    {
    }

    public AOrExprCaseLabel(
        TCase _case_,
        POrExpr _orExpr_,
        TColon _colon_)
    {
        setCase(_case_);

        setOrExpr(_orExpr_);

        setColon(_colon_);

    }
    public Object clone()
    {
        return new AOrExprCaseLabel(
            (TCase) cloneNode(_case_),
            (POrExpr) cloneNode(_orExpr_),
            (TColon) cloneNode(_colon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExprCaseLabel(this);
    }

    public TCase getCase()
    {
        return _case_;
    }

    public void setCase(TCase node)
    {
        if(_case_ != null)
        {
            _case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _case_ = node;
    }

    public POrExpr getOrExpr()
    {
        return _orExpr_;
    }

    public void setOrExpr(POrExpr node)
    {
        if(_orExpr_ != null)
        {
            _orExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _orExpr_ = node;
    }

    public TColon getColon()
    {
        return _colon_;
    }

    public void setColon(TColon node)
    {
        if(_colon_ != null)
        {
            _colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _colon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_case_)
            + toString(_orExpr_)
            + toString(_colon_);
    }

    void removeChild(Node child)
    {
        if(_case_ == child)
        {
            _case_ = null;
            return;
        }

        if(_orExpr_ == child)
        {
            _orExpr_ = null;
            return;
        }

        if(_colon_ == child)
        {
            _colon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_case_ == oldChild)
        {
            setCase((TCase) newChild);
            return;
        }

        if(_orExpr_ == oldChild)
        {
            setOrExpr((POrExpr) newChild);
            return;
        }

        if(_colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

    }
}
