/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AOrExprPrimaryExpr extends PPrimaryExpr
{
    private TLParenthese _lParenthese_;
    private POrExpr _orExpr_;
    private TRParenthese _rParenthese_;

    public AOrExprPrimaryExpr()
    {
    }

    public AOrExprPrimaryExpr(
        TLParenthese _lParenthese_,
        POrExpr _orExpr_,
        TRParenthese _rParenthese_)
    {
        setLParenthese(_lParenthese_);

        setOrExpr(_orExpr_);

        setRParenthese(_rParenthese_);

    }
    public Object clone()
    {
        return new AOrExprPrimaryExpr(
            (TLParenthese) cloneNode(_lParenthese_),
            (POrExpr) cloneNode(_orExpr_),
            (TRParenthese) cloneNode(_rParenthese_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExprPrimaryExpr(this);
    }

    public TLParenthese getLParenthese()
    {
        return _lParenthese_;
    }

    public void setLParenthese(TLParenthese node)
    {
        if(_lParenthese_ != null)
        {
            _lParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lParenthese_ = node;
    }

    public POrExpr getOrExpr()
    {
        return _orExpr_;
    }

    public void setOrExpr(POrExpr node)
    {
        if(_orExpr_ != null)
        {
            _orExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _orExpr_ = node;
    }

    public TRParenthese getRParenthese()
    {
        return _rParenthese_;
    }

    public void setRParenthese(TRParenthese node)
    {
        if(_rParenthese_ != null)
        {
            _rParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rParenthese_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lParenthese_)
            + toString(_orExpr_)
            + toString(_rParenthese_);
    }

    void removeChild(Node child)
    {
        if(_lParenthese_ == child)
        {
            _lParenthese_ = null;
            return;
        }

        if(_orExpr_ == child)
        {
            _orExpr_ = null;
            return;
        }

        if(_rParenthese_ == child)
        {
            _rParenthese_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lParenthese_ == oldChild)
        {
            setLParenthese((TLParenthese) newChild);
            return;
        }

        if(_orExpr_ == oldChild)
        {
            setOrExpr((POrExpr) newChild);
            return;
        }

        if(_rParenthese_ == oldChild)
        {
            setRParenthese((TRParenthese) newChild);
            return;
        }

    }
}
