/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AParamTypeSpecOpTypeSpec extends POpTypeSpec
{
    private PParamTypeSpec _paramTypeSpec_;

    public AParamTypeSpecOpTypeSpec()
    {
    }

    public AParamTypeSpecOpTypeSpec(
        PParamTypeSpec _paramTypeSpec_)
    {
        setParamTypeSpec(_paramTypeSpec_);

    }
    public Object clone()
    {
        return new AParamTypeSpecOpTypeSpec(
            (PParamTypeSpec) cloneNode(_paramTypeSpec_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamTypeSpecOpTypeSpec(this);
    }

    public PParamTypeSpec getParamTypeSpec()
    {
        return _paramTypeSpec_;
    }

    public void setParamTypeSpec(PParamTypeSpec node)
    {
        if(_paramTypeSpec_ != null)
        {
            _paramTypeSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _paramTypeSpec_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_paramTypeSpec_);
    }

    void removeChild(Node child)
    {
        if(_paramTypeSpec_ == child)
        {
            _paramTypeSpec_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_paramTypeSpec_ == oldChild)
        {
            setParamTypeSpec((PParamTypeSpec) newChild);
            return;
        }

    }
}
