/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class APlusAddExpr extends PAddExpr
{
    private PAddExpr _addExpr_;
    private TPlus _plus_;
    private PMultExpr _multExpr_;

    public APlusAddExpr()
    {
    }

    public APlusAddExpr(
        PAddExpr _addExpr_,
        TPlus _plus_,
        PMultExpr _multExpr_)
    {
        setAddExpr(_addExpr_);

        setPlus(_plus_);

        setMultExpr(_multExpr_);

    }
    public Object clone()
    {
        return new APlusAddExpr(
            (PAddExpr) cloneNode(_addExpr_),
            (TPlus) cloneNode(_plus_),
            (PMultExpr) cloneNode(_multExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusAddExpr(this);
    }

    public PAddExpr getAddExpr()
    {
        return _addExpr_;
    }

    public void setAddExpr(PAddExpr node)
    {
        if(_addExpr_ != null)
        {
            _addExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _addExpr_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PMultExpr getMultExpr()
    {
        return _multExpr_;
    }

    public void setMultExpr(PMultExpr node)
    {
        if(_multExpr_ != null)
        {
            _multExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multExpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_addExpr_)
            + toString(_plus_)
            + toString(_multExpr_);
    }

    void removeChild(Node child)
    {
        if(_addExpr_ == child)
        {
            _addExpr_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_multExpr_ == child)
        {
            _multExpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_addExpr_ == oldChild)
        {
            setAddExpr((PAddExpr) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_multExpr_ == oldChild)
        {
            setMultExpr((PMultExpr) newChild);
            return;
        }

    }
}
