/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ARaisesExpr extends PRaisesExpr
{
    private TRaises _raises_;
    private TLParenthese _lParenthese_;
    private PScopedName _scopedName_;
    private final LinkedList _commaScopedName_ = new TypedLinkedList(new CommaScopedName_Cast());
    private TRParenthese _rParenthese_;

    public ARaisesExpr()
    {
    }

    public ARaisesExpr(
        TRaises _raises_,
        TLParenthese _lParenthese_,
        PScopedName _scopedName_,
        List _commaScopedName_,
        TRParenthese _rParenthese_)
    {
        setRaises(_raises_);

        setLParenthese(_lParenthese_);

        setScopedName(_scopedName_);

        {
            this._commaScopedName_.clear();
            this._commaScopedName_.addAll(_commaScopedName_);
        }

        setRParenthese(_rParenthese_);

    }

    public ARaisesExpr(
        TRaises _raises_,
        TLParenthese _lParenthese_,
        PScopedName _scopedName_,
        XPCommaScopedName _commaScopedName_,
        TRParenthese _rParenthese_)
    {
        setRaises(_raises_);

        setLParenthese(_lParenthese_);

        setScopedName(_scopedName_);

        if(_commaScopedName_ != null)
        {
            while(_commaScopedName_ instanceof X1PCommaScopedName)
            {
                this._commaScopedName_.addFirst(((X1PCommaScopedName) _commaScopedName_).getPCommaScopedName());
                _commaScopedName_ = ((X1PCommaScopedName) _commaScopedName_).getXPCommaScopedName();
            }
            this._commaScopedName_.addFirst(((X2PCommaScopedName) _commaScopedName_).getPCommaScopedName());
        }

        setRParenthese(_rParenthese_);

    }
    public Object clone()
    {
        return new ARaisesExpr(
            (TRaises) cloneNode(_raises_),
            (TLParenthese) cloneNode(_lParenthese_),
            (PScopedName) cloneNode(_scopedName_),
            cloneList(_commaScopedName_),
            (TRParenthese) cloneNode(_rParenthese_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARaisesExpr(this);
    }

    public TRaises getRaises()
    {
        return _raises_;
    }

    public void setRaises(TRaises node)
    {
        if(_raises_ != null)
        {
            _raises_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _raises_ = node;
    }

    public TLParenthese getLParenthese()
    {
        return _lParenthese_;
    }

    public void setLParenthese(TLParenthese node)
    {
        if(_lParenthese_ != null)
        {
            _lParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lParenthese_ = node;
    }

    public PScopedName getScopedName()
    {
        return _scopedName_;
    }

    public void setScopedName(PScopedName node)
    {
        if(_scopedName_ != null)
        {
            _scopedName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _scopedName_ = node;
    }

    public LinkedList getCommaScopedName()
    {
        return _commaScopedName_;
    }

    public void setCommaScopedName(List list)
    {
        _commaScopedName_.clear();
        _commaScopedName_.addAll(list);
    }

    public TRParenthese getRParenthese()
    {
        return _rParenthese_;
    }

    public void setRParenthese(TRParenthese node)
    {
        if(_rParenthese_ != null)
        {
            _rParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rParenthese_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_raises_)
            + toString(_lParenthese_)
            + toString(_scopedName_)
            + toString(_commaScopedName_)
            + toString(_rParenthese_);
    }

    void removeChild(Node child)
    {
        if(_raises_ == child)
        {
            _raises_ = null;
            return;
        }

        if(_lParenthese_ == child)
        {
            _lParenthese_ = null;
            return;
        }

        if(_scopedName_ == child)
        {
            _scopedName_ = null;
            return;
        }

        if(_commaScopedName_.remove(child))
        {
            return;
        }

        if(_rParenthese_ == child)
        {
            _rParenthese_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_raises_ == oldChild)
        {
            setRaises((TRaises) newChild);
            return;
        }

        if(_lParenthese_ == oldChild)
        {
            setLParenthese((TLParenthese) newChild);
            return;
        }

        if(_scopedName_ == oldChild)
        {
            setScopedName((PScopedName) newChild);
            return;
        }

        for(ListIterator i = _commaScopedName_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rParenthese_ == oldChild)
        {
            setRParenthese((TRParenthese) newChild);
            return;
        }

    }

    private class CommaScopedName_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaScopedName node = (PCommaScopedName) o;

            if((node.parent() != null) &&
                (node.parent() != ARaisesExpr.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ARaisesExpr.this))
            {
                node.parent(ARaisesExpr.this);
            }

            return node;
        }
    }
}
