/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AScopedNameConstType extends PConstType
{
    private PScopedName _scopedName_;

    public AScopedNameConstType()
    {
    }

    public AScopedNameConstType(
        PScopedName _scopedName_)
    {
        setScopedName(_scopedName_);

    }
    public Object clone()
    {
        return new AScopedNameConstType(
            (PScopedName) cloneNode(_scopedName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScopedNameConstType(this);
    }

    public PScopedName getScopedName()
    {
        return _scopedName_;
    }

    public void setScopedName(PScopedName node)
    {
        if(_scopedName_ != null)
        {
            _scopedName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _scopedName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_scopedName_);
    }

    void removeChild(Node child)
    {
        if(_scopedName_ == child)
        {
            _scopedName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_scopedName_ == oldChild)
        {
            setScopedName((PScopedName) newChild);
            return;
        }

    }
}
