/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AShortConstType extends PConstType
{
    private TShort _short_;

    public AShortConstType()
    {
    }

    public AShortConstType(
        TShort _short_)
    {
        setShort(_short_);

    }
    public Object clone()
    {
        return new AShortConstType(
            (TShort) cloneNode(_short_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShortConstType(this);
    }

    public TShort getShort()
    {
        return _short_;
    }

    public void setShort(TShort node)
    {
        if(_short_ != null)
        {
            _short_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _short_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_short_);
    }

    void removeChild(Node child)
    {
        if(_short_ == child)
        {
            _short_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_short_ == oldChild)
        {
            setShort((TShort) newChild);
            return;
        }

    }
}
