/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AStateMemberValueElement extends PValueElement
{
    private PStateMember _stateMember_;

    public AStateMemberValueElement()
    {
    }

    public AStateMemberValueElement(
        PStateMember _stateMember_)
    {
        setStateMember(_stateMember_);

    }
    public Object clone()
    {
        return new AStateMemberValueElement(
            (PStateMember) cloneNode(_stateMember_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStateMemberValueElement(this);
    }

    public PStateMember getStateMember()
    {
        return _stateMember_;
    }

    public void setStateMember(PStateMember node)
    {
        if(_stateMember_ != null)
        {
            _stateMember_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stateMember_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stateMember_);
    }

    void removeChild(Node child)
    {
        if(_stateMember_ == child)
        {
            _stateMember_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stateMember_ == oldChild)
        {
            setStateMember((PStateMember) newChild);
            return;
        }

    }
}
