/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AStringParamTypeSpec extends PParamTypeSpec
{
    private PStringType _stringType_;

    public AStringParamTypeSpec()
    {
    }

    public AStringParamTypeSpec(
        PStringType _stringType_)
    {
        setStringType(_stringType_);

    }
    public Object clone()
    {
        return new AStringParamTypeSpec(
            (PStringType) cloneNode(_stringType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringParamTypeSpec(this);
    }

    public PStringType getStringType()
    {
        return _stringType_;
    }

    public void setStringType(PStringType node)
    {
        if(_stringType_ != null)
        {
            _stringType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stringType_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stringType_);
    }

    void removeChild(Node child)
    {
        if(_stringType_ == child)
        {
            _stringType_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stringType_ == oldChild)
        {
            setStringType((PStringType) newChild);
            return;
        }

    }
}
