/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AStructDclStructType extends PStructType
{
    private PStructDcl _structDcl_;

    public AStructDclStructType()
    {
    }

    public AStructDclStructType(
        PStructDcl _structDcl_)
    {
        setStructDcl(_structDcl_);

    }
    public Object clone()
    {
        return new AStructDclStructType(
            (PStructDcl) cloneNode(_structDcl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStructDclStructType(this);
    }

    public PStructDcl getStructDcl()
    {
        return _structDcl_;
    }

    public void setStructDcl(PStructDcl node)
    {
        if(_structDcl_ != null)
        {
            _structDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _structDcl_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_structDcl_);
    }

    void removeChild(Node child)
    {
        if(_structDcl_ == child)
        {
            _structDcl_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_structDcl_ == oldChild)
        {
            setStructDcl((PStructDcl) newChild);
            return;
        }

    }
}
