/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ATemplateTypeSpecSimpleTypeSpec extends PSimpleTypeSpec
{
    private PTemplateTypeSpec _templateTypeSpec_;

    public ATemplateTypeSpecSimpleTypeSpec()
    {
    }

    public ATemplateTypeSpecSimpleTypeSpec(
        PTemplateTypeSpec _templateTypeSpec_)
    {
        setTemplateTypeSpec(_templateTypeSpec_);

    }
    public Object clone()
    {
        return new ATemplateTypeSpecSimpleTypeSpec(
            (PTemplateTypeSpec) cloneNode(_templateTypeSpec_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATemplateTypeSpecSimpleTypeSpec(this);
    }

    public PTemplateTypeSpec getTemplateTypeSpec()
    {
        return _templateTypeSpec_;
    }

    public void setTemplateTypeSpec(PTemplateTypeSpec node)
    {
        if(_templateTypeSpec_ != null)
        {
            _templateTypeSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _templateTypeSpec_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_templateTypeSpec_);
    }

    void removeChild(Node child)
    {
        if(_templateTypeSpec_ == child)
        {
            _templateTypeSpec_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_templateTypeSpec_ == oldChild)
        {
            setTemplateTypeSpec((PTemplateTypeSpec) newChild);
            return;
        }

    }
}
