/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ATildeUnaryOperator extends PUnaryOperator
{
    private TTilde _tilde_;

    public ATildeUnaryOperator()
    {
    }

    public ATildeUnaryOperator(
        TTilde _tilde_)
    {
        setTilde(_tilde_);

    }
    public Object clone()
    {
        return new ATildeUnaryOperator(
            (TTilde) cloneNode(_tilde_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATildeUnaryOperator(this);
    }

    public TTilde getTilde()
    {
        return _tilde_;
    }

    public void setTilde(TTilde node)
    {
        if(_tilde_ != null)
        {
            _tilde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tilde_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tilde_);
    }

    void removeChild(Node child)
    {
        if(_tilde_ == child)
        {
            _tilde_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tilde_ == oldChild)
        {
            setTilde((TTilde) newChild);
            return;
        }

    }
}
