/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ATypeDeclaratorTypeDcl extends PTypeDcl
{
    private PTypeDeclarator _typeDeclarator_;

    public ATypeDeclaratorTypeDcl()
    {
    }

    public ATypeDeclaratorTypeDcl(
        PTypeDeclarator _typeDeclarator_)
    {
        setTypeDeclarator(_typeDeclarator_);

    }
    public Object clone()
    {
        return new ATypeDeclaratorTypeDcl(
            (PTypeDeclarator) cloneNode(_typeDeclarator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeDeclaratorTypeDcl(this);
    }

    public PTypeDeclarator getTypeDeclarator()
    {
        return _typeDeclarator_;
    }

    public void setTypeDeclarator(PTypeDeclarator node)
    {
        if(_typeDeclarator_ != null)
        {
            _typeDeclarator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _typeDeclarator_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_typeDeclarator_);
    }

    void removeChild(Node child)
    {
        if(_typeDeclarator_ == child)
        {
            _typeDeclarator_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_typeDeclarator_ == oldChild)
        {
            setTypeDeclarator((PTypeDeclarator) newChild);
            return;
        }

    }
}
