/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class ATypeIdDefinition extends PDefinition
{
    private PTypeId _typeId_;
    private TSemicolon _semicolon_;

    public ATypeIdDefinition()
    {
    }

    public ATypeIdDefinition(
        PTypeId _typeId_,
        TSemicolon _semicolon_)
    {
        setTypeId(_typeId_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new ATypeIdDefinition(
            (PTypeId) cloneNode(_typeId_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeIdDefinition(this);
    }

    public PTypeId getTypeId()
    {
        return _typeId_;
    }

    public void setTypeId(PTypeId node)
    {
        if(_typeId_ != null)
        {
            _typeId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _typeId_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_typeId_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_typeId_ == child)
        {
            _typeId_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_typeId_ == oldChild)
        {
            setTypeId((PTypeId) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
