/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AUlonglongBaseTypeSpec extends PBaseTypeSpec
{
    private PUnsignedLonglongInt _unsignedLonglongInt_;

    public AUlonglongBaseTypeSpec()
    {
    }

    public AUlonglongBaseTypeSpec(
        PUnsignedLonglongInt _unsignedLonglongInt_)
    {
        setUnsignedLonglongInt(_unsignedLonglongInt_);

    }
    public Object clone()
    {
        return new AUlonglongBaseTypeSpec(
            (PUnsignedLonglongInt) cloneNode(_unsignedLonglongInt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUlonglongBaseTypeSpec(this);
    }

    public PUnsignedLonglongInt getUnsignedLonglongInt()
    {
        return _unsignedLonglongInt_;
    }

    public void setUnsignedLonglongInt(PUnsignedLonglongInt node)
    {
        if(_unsignedLonglongInt_ != null)
        {
            _unsignedLonglongInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unsignedLonglongInt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_unsignedLonglongInt_);
    }

    void removeChild(Node child)
    {
        if(_unsignedLonglongInt_ == child)
        {
            _unsignedLonglongInt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_unsignedLonglongInt_ == oldChild)
        {
            setUnsignedLonglongInt((PUnsignedLonglongInt) newChild);
            return;
        }

    }
}
