/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AUnionForwardDcl extends PUnionForwardDcl
{
    private TUnion _union_;
    private TIdentifier _identifier_;

    public AUnionForwardDcl()
    {
    }

    public AUnionForwardDcl(
        TUnion _union_,
        TIdentifier _identifier_)
    {
        setUnion(_union_);

        setIdentifier(_identifier_);

    }
    public Object clone()
    {
        return new AUnionForwardDcl(
            (TUnion) cloneNode(_union_),
            (TIdentifier) cloneNode(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnionForwardDcl(this);
    }

    public TUnion getUnion()
    {
        return _union_;
    }

    public void setUnion(TUnion node)
    {
        if(_union_ != null)
        {
            _union_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _union_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_union_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_union_ == child)
        {
            _union_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_union_ == oldChild)
        {
            setUnion((TUnion) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

    }
}
