/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AValueDclValue extends PValue
{
    private PValueDcl _valueDcl_;

    public AValueDclValue()
    {
    }

    public AValueDclValue(
        PValueDcl _valueDcl_)
    {
        setValueDcl(_valueDcl_);

    }
    public Object clone()
    {
        return new AValueDclValue(
            (PValueDcl) cloneNode(_valueDcl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValueDclValue(this);
    }

    public PValueDcl getValueDcl()
    {
        return _valueDcl_;
    }

    public void setValueDcl(PValueDcl node)
    {
        if(_valueDcl_ != null)
        {
            _valueDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _valueDcl_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_valueDcl_);
    }

    void removeChild(Node child)
    {
        if(_valueDcl_ == child)
        {
            _valueDcl_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_valueDcl_ == oldChild)
        {
            setValueDcl((PValueDcl) newChild);
            return;
        }

    }
}
