/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AWcharConstType extends PConstType
{
    private TWchar _wchar_;

    public AWcharConstType()
    {
    }

    public AWcharConstType(
        TWchar _wchar_)
    {
        setWchar(_wchar_);

    }
    public Object clone()
    {
        return new AWcharConstType(
            (TWchar) cloneNode(_wchar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWcharConstType(this);
    }

    public TWchar getWchar()
    {
        return _wchar_;
    }

    public void setWchar(TWchar node)
    {
        if(_wchar_ != null)
        {
            _wchar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _wchar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_wchar_);
    }

    void removeChild(Node child)
    {
        if(_wchar_ == child)
        {
            _wchar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_wchar_ == oldChild)
        {
            setWchar((TWchar) newChild);
            return;
        }

    }
}
