/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import java.util.*;
import net.sf.eclipsecorba.idl.analysis.*;

public final class AWcharLiteral extends PLiteral
{
    private TWideCharacterLiteral _wideCharacterLiteral_;

    public AWcharLiteral()
    {
    }

    public AWcharLiteral(
        TWideCharacterLiteral _wideCharacterLiteral_)
    {
        setWideCharacterLiteral(_wideCharacterLiteral_);

    }
    public Object clone()
    {
        return new AWcharLiteral(
            (TWideCharacterLiteral) cloneNode(_wideCharacterLiteral_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWcharLiteral(this);
    }

    public TWideCharacterLiteral getWideCharacterLiteral()
    {
        return _wideCharacterLiteral_;
    }

    public void setWideCharacterLiteral(TWideCharacterLiteral node)
    {
        if(_wideCharacterLiteral_ != null)
        {
            _wideCharacterLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _wideCharacterLiteral_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_wideCharacterLiteral_);
    }

    void removeChild(Node child)
    {
        if(_wideCharacterLiteral_ == child)
        {
            _wideCharacterLiteral_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_wideCharacterLiteral_ == oldChild)
        {
            setWideCharacterLiteral((TWideCharacterLiteral) newChild);
            return;
        }

    }
}
