/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class Start extends Node
{
    private PSpecification _pSpecification_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PSpecification _pSpecification_,
        EOF _eof_)
    {
        setPSpecification(_pSpecification_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PSpecification) cloneNode(_pSpecification_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PSpecification getPSpecification()
    {
        return _pSpecification_;
    }

    public void setPSpecification(PSpecification node)
    {
        if(_pSpecification_ != null)
        {
            _pSpecification_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pSpecification_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pSpecification_ == child)
        {
            _pSpecification_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pSpecification_ == oldChild)
        {
            setPSpecification((PSpecification) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pSpecification_) +
            toString(_eof_);
    }
}
