/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class TAssign extends Token
{
    public TAssign()
    {
        super.setText("=");
    }

    public TAssign(int line, int pos)
    {
        super.setText("=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAssign(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAssign(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAssign text.");
    }
}
