/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class TBitXor extends Token
{
    public TBitXor()
    {
        super.setText("^");
    }

    public TBitXor(int line, int pos)
    {
        super.setText("^");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBitXor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBitXor(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBitXor text.");
    }
}
