/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class TBitOr extends Token
{
    public TBitOr()
    {
        super.setText("|");
    }

    public TBitOr(int line, int pos)
    {
        super.setText("|");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBitOr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBitOr(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBitOr text.");
    }
}
