/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class TBitAnd extends Token
{
    public TBitAnd()
    {
        super.setText("&");
    }

    public TBitAnd(int line, int pos)
    {
        super.setText("&");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBitAnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBitAnd(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBitAnd text.");
    }
}
