/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class TDoublecolon extends Token
{
    public TDoublecolon()
    {
        super.setText("::");
    }

    public TDoublecolon(int line, int pos)
    {
        super.setText("::");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDoublecolon(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDoublecolon(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDoublecolon text.");
    }
}
