/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class TShiftRight extends Token
{
    public TShiftRight()
    {
        super.setText(">>");
    }

    public TShiftRight(int line, int pos)
    {
        super.setText(">>");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TShiftRight(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTShiftRight(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TShiftRight text.");
    }
}
