/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class TShiftLeft extends Token
{
    public TShiftLeft()
    {
        super.setText("<<");
    }

    public TShiftLeft(int line, int pos)
    {
        super.setText("<<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TShiftLeft(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTShiftLeft(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TShiftLeft text.");
    }
}
