/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class X1PCommaIdentifier extends XPCommaIdentifier
{
    private XPCommaIdentifier _xPCommaIdentifier_;
    private PCommaIdentifier _pCommaIdentifier_;

    public X1PCommaIdentifier()
    {
    }

    public X1PCommaIdentifier(
        XPCommaIdentifier _xPCommaIdentifier_,
        PCommaIdentifier _pCommaIdentifier_)
    {
        setXPCommaIdentifier(_xPCommaIdentifier_);
        setPCommaIdentifier(_pCommaIdentifier_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPCommaIdentifier getXPCommaIdentifier()
    {
        return _xPCommaIdentifier_;
    }

    public void setXPCommaIdentifier(XPCommaIdentifier node)
    {
        if(_xPCommaIdentifier_ != null)
        {
            _xPCommaIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPCommaIdentifier_ = node;
    }

    public PCommaIdentifier getPCommaIdentifier()
    {
        return _pCommaIdentifier_;
    }

    public void setPCommaIdentifier(PCommaIdentifier node)
    {
        if(_pCommaIdentifier_ != null)
        {
            _pCommaIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pCommaIdentifier_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPCommaIdentifier_ == child)
        {
            _xPCommaIdentifier_ = null;
        }

        if(_pCommaIdentifier_ == child)
        {
            _pCommaIdentifier_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPCommaIdentifier_) +
            toString(_pCommaIdentifier_);
    }
}
