/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class X1PCommaInitParamDecl extends XPCommaInitParamDecl
{
    private XPCommaInitParamDecl _xPCommaInitParamDecl_;
    private PCommaInitParamDecl _pCommaInitParamDecl_;

    public X1PCommaInitParamDecl()
    {
    }

    public X1PCommaInitParamDecl(
        XPCommaInitParamDecl _xPCommaInitParamDecl_,
        PCommaInitParamDecl _pCommaInitParamDecl_)
    {
        setXPCommaInitParamDecl(_xPCommaInitParamDecl_);
        setPCommaInitParamDecl(_pCommaInitParamDecl_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPCommaInitParamDecl getXPCommaInitParamDecl()
    {
        return _xPCommaInitParamDecl_;
    }

    public void setXPCommaInitParamDecl(XPCommaInitParamDecl node)
    {
        if(_xPCommaInitParamDecl_ != null)
        {
            _xPCommaInitParamDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPCommaInitParamDecl_ = node;
    }

    public PCommaInitParamDecl getPCommaInitParamDecl()
    {
        return _pCommaInitParamDecl_;
    }

    public void setPCommaInitParamDecl(PCommaInitParamDecl node)
    {
        if(_pCommaInitParamDecl_ != null)
        {
            _pCommaInitParamDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pCommaInitParamDecl_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPCommaInitParamDecl_ == child)
        {
            _xPCommaInitParamDecl_ = null;
        }

        if(_pCommaInitParamDecl_ == child)
        {
            _pCommaInitParamDecl_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPCommaInitParamDecl_) +
            toString(_pCommaInitParamDecl_);
    }
}
