/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class X1PExport extends XPExport
{
    private XPExport _xPExport_;
    private PExport _pExport_;

    public X1PExport()
    {
    }

    public X1PExport(
        XPExport _xPExport_,
        PExport _pExport_)
    {
        setXPExport(_xPExport_);
        setPExport(_pExport_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPExport getXPExport()
    {
        return _xPExport_;
    }

    public void setXPExport(XPExport node)
    {
        if(_xPExport_ != null)
        {
            _xPExport_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPExport_ = node;
    }

    public PExport getPExport()
    {
        return _pExport_;
    }

    public void setPExport(PExport node)
    {
        if(_pExport_ != null)
        {
            _pExport_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pExport_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPExport_ == child)
        {
            _xPExport_ = null;
        }

        if(_pExport_ == child)
        {
            _pExport_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPExport_) +
            toString(_pExport_);
    }
}
