/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class X1PValueElement extends XPValueElement
{
    private XPValueElement _xPValueElement_;
    private PValueElement _pValueElement_;

    public X1PValueElement()
    {
    }

    public X1PValueElement(
        XPValueElement _xPValueElement_,
        PValueElement _pValueElement_)
    {
        setXPValueElement(_xPValueElement_);
        setPValueElement(_pValueElement_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPValueElement getXPValueElement()
    {
        return _xPValueElement_;
    }

    public void setXPValueElement(XPValueElement node)
    {
        if(_xPValueElement_ != null)
        {
            _xPValueElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPValueElement_ = node;
    }

    public PValueElement getPValueElement()
    {
        return _pValueElement_;
    }

    public void setPValueElement(PValueElement node)
    {
        if(_pValueElement_ != null)
        {
            _pValueElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pValueElement_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPValueElement_ == child)
        {
            _xPValueElement_ = null;
        }

        if(_pValueElement_ == child)
        {
            _pValueElement_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPValueElement_) +
            toString(_pValueElement_);
    }
}
