/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class X2PCommaScopedName extends XPCommaScopedName
{
    private PCommaScopedName _pCommaScopedName_;

    public X2PCommaScopedName()
    {
    }

    public X2PCommaScopedName(
        PCommaScopedName _pCommaScopedName_)
    {
        setPCommaScopedName(_pCommaScopedName_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PCommaScopedName getPCommaScopedName()
    {
        return _pCommaScopedName_;
    }

    public void setPCommaScopedName(PCommaScopedName node)
    {
        if(_pCommaScopedName_ != null)
        {
            _pCommaScopedName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pCommaScopedName_ = node;
    }

    void removeChild(Node child)
    {
        if(_pCommaScopedName_ == child)
        {
            _pCommaScopedName_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pCommaScopedName_);
    }
}
