/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class X2PExport extends XPExport
{
    private PExport _pExport_;

    public X2PExport()
    {
    }

    public X2PExport(
        PExport _pExport_)
    {
        setPExport(_pExport_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PExport getPExport()
    {
        return _pExport_;
    }

    public void setPExport(PExport node)
    {
        if(_pExport_ != null)
        {
            _pExport_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pExport_ = node;
    }

    void removeChild(Node child)
    {
        if(_pExport_ == child)
        {
            _pExport_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pExport_);
    }
}
