/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.eclipsecorba.idl.node;

import net.sf.eclipsecorba.idl.analysis.*;

public final class X2PFixedArraySize extends XPFixedArraySize
{
    private PFixedArraySize _pFixedArraySize_;

    public X2PFixedArraySize()
    {
    }

    public X2PFixedArraySize(
        PFixedArraySize _pFixedArraySize_)
    {
        setPFixedArraySize(_pFixedArraySize_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PFixedArraySize getPFixedArraySize()
    {
        return _pFixedArraySize_;
    }

    public void setPFixedArraySize(PFixedArraySize node)
    {
        if(_pFixedArraySize_ != null)
        {
            _pFixedArraySize_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pFixedArraySize_ = node;
    }

    void removeChild(Node child)
    {
        if(_pFixedArraySize_ == child)
        {
            _pFixedArraySize_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pFixedArraySize_);
    }
}
